image: microsoft/dotnet:2-sdk

stages:
- build
- publish

build:
  stage: build
  script:
  - dotnet test
  - dotnet pack -c Release --include-symbols -o $CI_PROJECT_DIR/Build/
  artifacts:
    paths:
    - Build/*.nupkg
    - Build/*.snupkg
    expire_in: 1 week

publish:
  stage: publish
  only:
    - nuget
  script:
  - cd $CI_PROJECT_DIR/Build/
  - dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY
  dependencies:
  - build